version: '3.1'

services:

  tasks_management_db_service:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
        - ./provising/database/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: VGhpcyBpcyB0aGUgY29kZQ==
    ports:
      - 3306:3306
